version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --timeout 120 --workers 3 encryption_project.wsgi:application
    volumes:
      - .:/app
      - sqlite_data:/app/db  # ✅ Persistent volume for SQLite database
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - DATABASE_URL=sqlite:///db/db.sqlite3  # ✅ Updated path for persistence

volumes:
  sqlite_data:
